import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { HelpWidget } from "../components/HelpWidget";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Help Chat Ap</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HelpWidget />
      </main>
    </>
  );
};

export default Home;
